package com.clockstopper.app

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Sanity-check unit test generated by Android Studio.
 * Real business-logic tests live in the `domain/` sub-package.
 */
class ExampleUnitTest {
    @Test
    fun addition_isCorrect() {
        assertEquals(4, 2 + 2)
    }
}
